ALTER TABLE SURVEY."option" ADD CONSTRAINT option_pk PRIMARY KEY (id);
ALTER TABLE SURVEY."question" ADD CONSTRAINT question_pk PRIMARY KEY (id);
ALTER TABLE SURVEY."survey" ADD CONSTRAINT survey_pk PRIMARY KEY (id);